// default package
// Generated 13 Mar 2023, 17:56:20 by Hibernate Tools 6.1.7.Final
package com.rosebloom.models.entities;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="order_details"
    ,catalog="rosebloom"
)
public class OrderDetails  implements java.io.Serializable {


     private OrderDetailsId id;
     private Orders orders;
     private Product product;
     private Integer quantity;
     private Double price;

    public OrderDetails() {
    }

	
    public OrderDetails(OrderDetailsId id, Orders orders, Product product) {
        this.id = id;
        this.orders = orders;
        this.product = product;
    }
    public OrderDetails(OrderDetailsId id, Orders orders, Product product, Integer quantity, Double price) {
       this.id = id;
       this.orders = orders;
       this.product = product;
       this.quantity = quantity;
       this.price = price;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
    @AttributeOverride(name="orderId", column=@Column(name="order_id", nullable=false) ), 
    @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public OrderDetailsId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailsId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false, insertable=false, updatable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


