// default package
// Generated 13 Mar 2023, 17:56:20 by Hibernate Tools 6.1.7.Final
package com.rosebloom.models.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * ProductImageId generated by hbm2java
 */
@Embeddable
public class ProductImageId  implements java.io.Serializable {


     private int imgId;
     private int productId;

    public ProductImageId() {
    }

    public ProductImageId(int imgId, int productId) {
       this.imgId = imgId;
       this.productId = productId;
    }
   


    @Column(name="img_id", nullable=false)
    public int getImgId() {
        return this.imgId;
    }
    
    public void setImgId(int imgId) {
        this.imgId = imgId;
    }


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductImageId) ) return false;
		 ProductImageId castOther = ( ProductImageId ) other; 
         
		 return (this.getImgId()==castOther.getImgId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getImgId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


