// default package
// Generated 13 Mar 2023, 17:56:20 by Hibernate Tools 6.1.7.Final
package com.rosebloom.models.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="rosebloom"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class User  implements java.io.Serializable {


     private int id;
     private String name;
     private String password;
     private String email;
     private String address;
     private String birthdate;
     private String phone;
     private int creditLimit;
     private String intrest;
     private String job;
     private int isAdmin;
     private Set<Cart> carts = new HashSet(0);
     private Set<Orders> orderses = new HashSet(0);
     private Set<UserInterest> userInterests = new HashSet(0);

    public User() {
    }

	
    public User(int id, String name, String password, String email, String address, String birthdate, String phone, int creditLimit, int isAdmin) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.email = email;
        this.address = address;
        this.birthdate = birthdate;
        this.phone = phone;
        this.creditLimit = creditLimit;
        this.isAdmin = isAdmin;
    }
    public User(int id, String name, String password, String email, String address, String birthdate, String phone, int creditLimit, String intrest, String job, int isAdmin, Set<Cart> carts, Set<Orders> orderses, Set<UserInterest> userInterests) {
       this.id = id;
       this.name = name;
       this.password = password;
       this.email = email;
       this.address = address;
       this.birthdate = birthdate;
       this.phone = phone;
       this.creditLimit = creditLimit;
       this.intrest = intrest;
       this.job = job;
       this.isAdmin = isAdmin;
       this.carts = carts;
       this.orderses = orderses;
       this.userInterests = userInterests;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="password", nullable=false, length=300)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="address", nullable=false, length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="birthdate", nullable=false, length=45)
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="phone", nullable=false, length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="creditLimit", nullable=false)
    public int getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(int creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="intrest", length=45)
    public String getIntrest() {
        return this.intrest;
    }
    
    public void setIntrest(String intrest) {
        this.intrest = intrest;
    }

    
    @Column(name="job", length=45)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

    
    @Column(name="isAdmin", nullable=false)
    public int getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(int isAdmin) {
        this.isAdmin = isAdmin;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserInterest> getUserInterests() {
        return this.userInterests;
    }
    
    public void setUserInterests(Set<UserInterest> userInterests) {
        this.userInterests = userInterests;
    }




}


