// default package
// Generated 13 Mar 2023, 17:56:20 by Hibernate Tools 6.1.7.Final
package com.rosebloom.models.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * UserInterestId generated by hbm2java
 */
@Embeddable
public class UserInterestId  implements java.io.Serializable {


     private String interest;
     private int userId;

    public UserInterestId() {
    }

    public UserInterestId(String interest, int userId) {
       this.interest = interest;
       this.userId = userId;
    }
   


    @Column(name="interest", nullable=false, length=45)
    public String getInterest() {
        return this.interest;
    }
    
    public void setInterest(String interest) {
        this.interest = interest;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserInterestId) ) return false;
		 UserInterestId castOther = ( UserInterestId ) other; 
         
		 return ( (this.getInterest()==castOther.getInterest()) || ( this.getInterest()!=null && castOther.getInterest()!=null && this.getInterest().equals(castOther.getInterest()) ) )
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInterest() == null ? 0 : this.getInterest().hashCode() );
         result = 37 * result + this.getUserId();
         return result;
   }   


}


