// default package
// Generated 14 Mar 2023, 16:06:02 by Hibernate Tools 6.1.7.Final
package com.rosebloom.controllers.persistence.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="rosebloom"
)
public class Category  implements java.io.Serializable {


    private Integer categoryId;
    private Category category;
    private String categoryName;
    private Integer isDeleted;
    private Set<User> users = new HashSet(0);
    private Set<Category> categories = new HashSet(0);
    private Set<Product> products = new HashSet(0);

    public Category() {
    }

	
    public Category(String categoryName) {
        this.categoryName = categoryName;
    }
    public Category(Category category, String categoryName, Integer isDeleted, Set<User> users, Set<Category> categories, Set<Product> products) {
       this.category = category;
       this.categoryName = categoryName;
       this.isDeleted = isDeleted;
       this.users = users;
       this.categories = categories;
       this.products = products;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="category_id", unique=true, nullable=false)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="category_name", nullable=false, length=50)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="isDeleted")
    public Integer getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_interest", catalog="rosebloom", joinColumns = { 
    @JoinColumn(name="interest_category_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
    @JoinColumn(name="user_id", nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="product_category", catalog="rosebloom", joinColumns = { 
    @JoinColumn(name="category_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
    @JoinColumn(name="product_id", nullable=false, updatable=false) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


