// default package
// Generated 14 Mar 2023, 16:06:02 by Hibernate Tools 6.1.7.Final
package com.rosebloom.controllers.persistence.entities;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * ProductImage generated by hbm2java
 */
@Entity
@Table(name="product_image"
    ,catalog="rosebloom"
)
public class ProductImage  implements java.io.Serializable {


    private ProductImageId id;
    private Product product;
    private String image;

    public ProductImage() {
    }

    public ProductImage(ProductImageId id, Product product, String image) {
       this.id = id;
       this.product = product;
       this.image = image;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="imgId", column=@Column(name="img_id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public ProductImageId getId() {
        return this.id;
    }
    
    public void setId(ProductImageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="image", nullable=false)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


